cloudbees/lighthouse-githubapp

OWNERS
=> fix: add missing owners file

.gitignore, Dockerfile, Makefile, charts/lighthouse-githubapp/Chart.yaml, charts/lighthouse-githubapp/Makefile, charts/lighthouse-githubapp/templates/NOTES.txt, charts/lighthouse-githubapp/templates/_helper.tpl, charts/lighthouse-githubapp/templates/deployment.yaml, charts/lighthouse-githubapp/templates/ingress.yaml, charts/lighthouse-githubapp/templates/ksvc.yaml, charts/lighthouse-githubapp/templates/secret.yaml, charts/lighthouse-githubapp/templates/service.yaml, charts/lighthouse-githubapp/values.yaml, charts/preview/Chart.yaml, charts/preview/Makefile, charts/preview/requirements.yaml, charts/preview/values.yaml, jenkins-x.yml, updatebot.sh
=> feat: Add initial build files and charts

charts/lighthouse-githubapp/templates/deployment.yaml, go.mod, go.sum, pkg/hook/hook.go
by using the kubeConfig that comes from the tenant service
=> fix: switch to nicer mechanism to create remote k8s connections

pkg/hook/hook.go
so we eagerly create the metapipeline client
=> fix: fix regression in lighthouse

pkg/hook/github_app.go
=> feat: handle errors better

pkg/hook/github_app.go, pkg/hook/scm.go
=> feat: add additional logging

pkg/hook/github_app.go
=> fix: create apps scm client

pkg/hook/github_app.go
=> feat: remove duplicate log line

main.go, pkg/hook/hook.go, pkg/hook/scm.go
Allow the application to close when pressing ctrl+c
Fix formatting issues
=> fix: handle shutdown hook

pkg/hook/github_app.go
=> fix: output correct url for an github app install

pkg/hook/constants.go, pkg/hook/handle_token_valid.go, pkg/hook/helpers.go, pkg/hook/hook.go, pkg/hook/scm.go
and add temporary debugging checks to verify scm tokens before we invoke lighthouse
=> fix: add a debugging REST API for install tokens

main.go, pkg/hook/scm.go
especially if they are going to expire soon
=> fix: lets cache tokens for a shorter amount

pkg/hook/github_app.go
Signed-off-by: Cai Cooper <caicooper82@gmail.com>
=> feat: adding github app name to the installation response

go.mod, go.sum, pkg/flags/flags.go, pkg/hook/hook.go
and upgrade lighthouse to latest
=> fix: pass in better logrus context to lighthouse

pkg/hook/handle_webhook.go
Reverts cloudbees/lighthouse-githubapp#542
=> Revert "Chore: attempt to log the failing webhook"

pkg/schedulers/generator.go
Signed-off-by: Mark Cox <markcox20@hotmail.com>
=> chore: use jx-logging

pkg/hook/hook.go
In the retry case, this is somehow ending up with Lighthouse returning a 400, which I can't figure out, so honestly, I'm just trying things. =)
Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>
=> fix: Recreate the signature/request/etc for each relay attempt, log more

pkg/hook/hook.go
I think we may be trying to relay just as the webhook controller(s) are restarting due to the updated Prow config. Based on logs, I'm pretty sure we're hitting _some_ error in the `o.client.Do(req)` but can't tell what. So...let's try this?
Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>
=> chore: Log earlier, delay slightly on retry

pkg/hook/handle_webhook_test.go, pkg/hook/hook.go
Signed-off-by: Mark Cox <markcox20@hotmail.com>
=> chore: log insecure value from db

pkg/hook/handle_webhook.go
fixes cloudbees/arcalos-security#39
=> chore: wrap body read with a limitreader

jenkins-x.yml
fixes https://github.com/cloudbees/arcalos/issues/151
=> chore: remove use of jx step credential

charts/lighthouse-githubapp/templates/saas-secret.yaml, charts/lighthouse-githubapp/templates/secret.yaml, jenkins-x.yml
workaround for https://github.com/cloudbees/arcalos/issues/1189
=> chore: temporarily prevent jx preview command
